apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello_app
  name: hello_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_app
  template:
    metadata:
      labels:
        app: hello_app
    spec:
      containers:
      - image: mariamkasssab/iti_project:v${BUILD_NUMBER}
        name: hello_app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources: {}
